name: athena
description: A new Flutter project.
publish_to: "none"

version: 2.0.1+75

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_markdown: ^0.7.3
  flutter_markdown_latex: ^0.3.3
  flutter_riverpod: ^2.5.1
  flutter_slidable: ^3.0.0
  google_fonts: ^6.2.1
  go_router: ^14.2.1
  http: ^1.1.0
  hugeicons: ^0.0.7
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  logger: ^2.0.2+1
  markdown: ^7.2.2
  path_provider: ^2.0.15
  riverpod_annotation: ^2.3.5
  system_tray: ^2.0.2
  window_manager: ^0.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.11
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  isar_generator: ^3.1.0+1
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - asset/
    - asset/image/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "asset/image/launcher_icon_ios_512x512.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
  windows:
    generate: true
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "asset/image/launcher_icon_macos_512x512.png"
