name: athena
description: A new Flutter project.
publish_to: "none"

version: 2.0.1+26

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  creator: ^0.3.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.0.5
  go_router: ^12.1.1
  logger: ^2.0.2+1
  flutter_slidable: ^3.0.0
  system_tray: ^2.0.2
  path_provider: ^2.0.15
  window_manager: ^0.3.5
  markdown_widget: ^2.2.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  flutter_lints: ^3.0.1
  isar_generator: ^3.0.5
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - asset/
    - asset/image/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "asset/image/launcher_icon_ios_512x512.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
  windows:
    generate: true
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "asset/image/launcher_icon_macos_512x512.png"
