name: athena
description: A new Flutter project.
publish_to: "none"

version: 2.1.1+461

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^9.2.2
  async: ^2.13.0
  cached_network_image: ^3.3.1
  dart_mcp: ^0.2.2
  device_info_plus: ^11.3.0
  file_picker: ^9.0.2
  flutter_markdown: ^0.7.6+1
  flutter_markdown_latex: ^0.3.4
  flutter_riverpod: ^2.5.1
  flutter_slidable: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  gpt_markdown: 1.0.9
  html_parser_plus: ^0.1.4
  http: ^1.1.0
  hugeicons: ^0.0.10
  image_gallery_saver_plus: ^4.0.1
  isar:
    version: ^3.1.8
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs:
    version: ^3.1.8
    hosted: https://pub.isar-community.dev/
  logger: ^2.0.2+1
  markdown: ^7.2.2
  # mcp_dart:
  #   git:
  #     url: git@github.com:CalsRanna/mcp_dart.git
  openai_dart: ^0.4.5
  package_info_plus: ^8.2.1
  path_provider: ^2.0.15
  process: ^5.0.3
  riverpod_annotation: ^2.3.5
  stream_channel: ^2.1.4
  synchronized: ^3.3.1
  system_tray: ^2.0.2
  tavily_dart: ^0.1.0+1
  url_launcher: ^6.3.1
  visibility_detector: ^0.4.0+2
  window_manager: ^0.4.3

dependency_overrides:
  flutter_math_fork: ^0.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^9.0.0
  build_runner: ^2.4.11
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^5.0.0
  isar_generator:
    version: ^3.1.8
    hosted: https://pub.isar-community.dev/
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - asset/
    - asset/image/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "asset/image/launcher_icon_ios_512x512.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
  windows:
    generate: true
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "asset/image/launcher_icon_macos_512x512.png"
