class PresetProvider {
  static const providers = [
    {
      'is_preset': true,
      'api_key': '',
      'name': 'Deep Seek',
      'base_url': 'https://api.deepseek.com/v1',
      'models': [
        {
          'name': 'DeepSeek-R1-0528',
          'model_id': 'deepseek-reasoner',
          'context_window': 64000,
          'input_price': 4.0,
          'output_price': 16.0,
          'reasoning': true,
          'vision': false,
        },
        {
          'name': 'DeepSeek-V3-0324',
          'model_id': 'deepseek-chat',
          'context_window': 64000,
          'input_price': 2.0,
          'output_price': 8.0,
          'reasoning': false,
          'vision': false,
        }
      ]
    },
    {
      'is_preset': true,
      'api_key': '',
      'name': 'Open Router',
      'base_url': 'https://openrouter.ai/api/v1',
      'models': [
        {
          'name': 'Anthropic: Claude Sonnet 4',
          'model_id': 'anthropic/claude-sonnet-4',
          'context_window': 200000,
          'input_price': 3.0,
          'output_price': 15.0,
          'reasoning': false,
          'vision': true,
        },
        {
          'name': 'Anthropic: Claude Opus 4',
          'model_id': 'anthropic/claude-opus-4',
          'context_window': 200000,
          'input_price': 15.0,
          'output_price': 75.0,
          'reasoning': false,
          'vision': true,
        },
        {
          'name': 'DeepSeek: DeepSeek V3 0324',
          'model_id': 'deepseek/deepseek-chat-v3-0324',
          'context_window': 163840,
          'input_price': 0.28,
          'output_price': 0.88,
          'reasoning': false,
          'vision': false,
        },
        {
          'name': 'DeepSeek: R1 0528',
          'model_id': 'deepseek/deepseek-r1-0528',
          'context_window': 128000,
          'input_price': 0.5,
          'output_price': 2.15,
          'reasoning': true,
          'vision': false,
        },
        {
          'name': 'Google: Gemini 2.5 Flash',
          'model_id': 'google/gemini-2.5-flash',
          'context_window': 1048576,
          'input_price': 0.3,
          'output_price': 2.5,
          'reasoning': true,
          'vision': true,
        },
        {
          'name': 'Google: Gemini 2.5 Pro',
          'model_id': 'google/gemini-2.5-pro',
          'context_window': 1048576,
          'input_price': 1.25,
          'output_price': 10.0,
          'reasoning': true,
          'vision': true,
        },
        {
          'name': 'Meta: Llama 4 Maverick',
          'model_id': 'meta-llama/llama-4-maverick',
          'context_window': 1048576,
          'input_price': 0.15,
          'output_price': 0.6,
          'reasoning': true,
          'vision': true,
        },
        {
          'name': 'OpenAI: GPT-4.1',
          'model_id': 'openai/gpt-4.1',
          'context_window': 1047576,
          'input_price': 2.0,
          'output_price': 8.0,
          'reasoning': false,
          'vision': false,
        },
        {
          'name': 'Qwen: Qwen3 235B A22B',
          'model_id': 'qwen/qwen3-235b-a22b',
          'context_window': 40960,
          'input_price': 0.13,
          'output_price': 0.6,
          'reasoning': true,
          'vision': false,
        },
        {
          'name': 'xAI: Grok 4',
          'model_id': 'x-ai/grok-4',
          'context_window': 256000,
          'input_price': 3.0,
          'output_price': 15.0,
          'reasoning': true,
          'vision': true,
        }
      ]
    },
    {
      'is_preset': true,
      'api_key': '',
      'name': '阿里云百炼',
      'base_url': 'https://dashscope.aliyuncs.com/compatible-mode/v1',
      'models': [
        {
          'name': 'DeepSeek-R1',
          'model_id': 'deepseek-r1',
          'context_window': 131072,
          'input_price': 4.0,
          'output_price': 16.0,
          'reasoning': true,
          'vision': false,
        },
        {
          'name': 'DeepSeek-V3',
          'model_id': 'deepseek-v3',
          'context_window': 65536,
          'input_price': 2.0,
          'output_price': 8.0,
          'reasoning': false,
          'vision': false,
        },
        {
          'name': '通义千问-Max',
          'model_id': 'qwen-max',
          'context_window': 32768,
          'input_price': 2.4,
          'output_price': 9.6,
          'reasoning': false,
          'vision': false,
        },
        {
          'name': '通义千问-Plus',
          'model_id': 'qwen-plus',
          'context_window': 131072,
          'input_price': 0.8,
          'output_price': 2.0,
          'reasoning': false,
          'vision': false,
        },
        {
          'name': '通义千问-Turbo',
          'model_id': 'qwen-turbo',
          'context_window': 1000000,
          'input_price': 0.3,
          'output_price': 0.6,
          'reasoning': false,
          'vision': false,
        }
      ]
    },
    {
      'is_preset': true,
      'api_key': '',
      'name': '硅基流动',
      'base_url': 'https://api.siliconflow.cn/v1',
      'models': [
        {
          'name': 'DeepSeek-R1',
          'model_id': 'deepseek-ai/DeepSeek-R1',
          'context_window': 160000,
          'input_price': 4.0,
          'output_price': 16.0,
          'reasoning': true,
          'vision': false,
        },
        {
          'name': 'DeepSeek-V3',
          'model_id': 'deepseek-ai/DeepSeek-V3',
          'context_window': 64000,
          'input_price': 2.0,
          'output_price': 8.0,
          'reasoning': false,
          'vision': false,
        }
      ]
    },
    {
      'is_preset': true,
      'api_key': '',
      'name': '火山方舟',
      'base_url': 'https://ark.cn-beijing.volces.com/api/v3',
      'models': [
        {
          'name': 'DeepSeek-R1',
          'model_id': 'deepseek-r1-250528',
          'context_window': 128000,
          'input_price': 4.0,
          'output_price': 16.0,
          'reasoning': true,
          'vision': false,
        },
        {
          'name': 'DeepSeek-V3',
          'model_id': 'deepseek-v3-250324',
          'context_window': 128000,
          'input_price': 2.0,
          'output_price': 8.0,
          'reasoning': false,
          'vision': false,
        },
        {
          'name': 'Doubao-Seed-1.6-thinking',
          'model_id': 'doubao-seed-1-6-thinking-250615',
          'context_window': 256000,
          'input_price': 0.8,
          'output_price': 8.0,
          'reasoning': true,
          'vision': true,
        },
        {
          'name': 'Doubao-Seed-1.6-flash',
          'model_id': 'doubao-seed-1-6-flash-250615',
          'context_window': 256000,
          'input_price': 0.15,
          'output_price': 1.5,
          'reasoning': true,
          'vision': true,
        }
      ]
    }
  ];
}
