class PresetProvider {
  static const providers = [
    {
      'is_preset': true,
      'api_key': '',
      'name': 'Deep Seek',
      'base_url': 'https://api.deepseek.com/v1',
      'models': [
        {
          'name': 'DeepSeek-R1-0528',
          'model_id': 'deepseek-reasoner',
          'context_window': '64K context',
          'input_price': '¥4/M input tokens',
          'output_price': '¥16/M output tokens',
          'released_at': 'Created 2025/05/28',
          'reasoning': true,
          'vision': false,
        },
        {
          'name': 'DeepSeek-V3-0324',
          'model_id': 'deepseek-chat',
          'context_window': '64K context',
          'input_price': '¥2/M input tokens',
          'output_price': '¥8/M output tokens',
          'released_at': 'Created 2025/03/25',
          'reasoning': false,
          'vision': false,
        },
      ],
    },
    {
      'is_preset': true,
      'api_key': '',
      'name': 'Open Router',
      'base_url': 'https://openrouter.ai/api/v1',
      'models': [
        {
          'name': 'Anthropic: Claude Sonnet 4',
          'model_id': 'anthropic/claude-sonnet-4',
          'context_window': '200,000 context',
          'input_price': r'$3/M input tokens',
          'output_price': r'$15/M output tokens',
          'released_at': 'Created May 22, 2025',
          'reasoning': false,
          'vision': true,
        },
        {
          'name': 'Anthropic: Claude Opus 4',
          'model_id': 'anthropic/claude-opus-4',
          'context_window': '200,000 context',
          'input_price': r'$15/M input tokens',
          'output_price': r'$75/M output tokens',
          'released_at': 'Created May 22, 2025',
          'reasoning': false,
          'vision': true,
        },
        {
          'name': 'DeepSeek: DeepSeek V3 0324',
          'model_id': 'deepseek/deepseek-chat-v3-0324',
          'context_window': '163,840 context',
          'input_price': r'$0.28/M input tokens',
          'output_price': r'$0.88/M output tokens',
          'released_at': 'Created Mar 24, 2025',
          'reasoning': false,
          'vision': false,
        },
        {
          'name': 'DeepSeek: R1 0528',
          'model_id': 'deepseek/deepseek-r1-0528',
          'context_window': '128,000 context',
          'input_price': r'$0.5/M input tokens',
          'output_price': r'$2.15/M output tokens',
          'released_at': 'Created May 28, 2025',
          'reasoning': true,
          'vision': false,
        },
        {
          'name': 'Google: Gemini 2.5 Flash',
          'model_id': 'google/gemini-2.5-flash',
          'context_window': '1,048,576 context',
          'input_price': r'$0.30/M input tokens',
          'output_price': r'$2.50/M output tokens',
          'released_at': 'Created Jun 17, 2025',
          'reasoning': false,
          'vision': false,
        },
        {
          'name': 'Google: Gemini 2.5 Pro',
          'model_id': 'google/gemini-2.5-pro',
          'context_window': '1,048,576 context',
          'input_price': r'Starting at $1.25/M input tokens',
          'output_price': r'Starting at $10/M output tokens',
          'released_at': 'Created Jun 17, 2025',
          'reasoning': true,
          'vision': false,
        },
        {
          'name': 'Meta: Llama 4 Maverick',
          'model_id': 'meta-llama/llama-4-maverick',
          'context_window': '1,048,576 context',
          'input_price': r'$0.15/M input tokens',
          'output_price': r'$0.60/M output tokens',
          'released_at': 'Created Apr 5, 2025',
          'reasoning': true,
          'vision': true,
        },
        {
          'name': 'OpenAI: GPT-4.1',
          'model_id': 'openai/gpt-4.1',
          'context_window': '1,047,576 context',
          'input_price': r'$2/M input tokens',
          'output_price': r'$8/M output tokens',
          'released_at': 'Created Apr 14, 2025',
          'reasoning': false,
          'vision': false,
        },
        {
          'name': 'Qwen: Qwen3 235B A22B',
          'model_id': 'qwen/qwen3-235b-a22b',
          'context_window': '40,960 context',
          'input_price': r'$0.13/M input tokens',
          'output_price': r'$0.60/M output tokens',
          'released_at': 'Created Apr 28, 2025',
          'reasoning': true,
          'vision': false,
        },
        {
          'name': 'xAI: Grok 4',
          'model_id': 'x-ai/grok-4',
          'context_window': '256,000 context',
          'input_price': r'$3/M input tokens',
          'output_price': r'$15/M output tokens',
          'released_at': 'Created Jul 9, 2025',
          'reasoning': true,
          'vision': true,
        },
        {
          'name': 'OpenAI: GPT-5 Chat',
          'model_id': 'openai/gpt-5',
          'context_window': '128,000 context',
          'input_price': r'$1.25/M input tokens',
          'output_price': r'$10/M output tokens',
          'released_at': 'Created Aug 7, 2025',
          'reasoning': false,
          'vision': false,
        },
        {
          'name': 'Anthropic: Claude Sonnet 4.5',
          'model_id': 'anthropic/claude-sonnet-4.5',
          'context_window': '1,000,000 context',
          'input_price': r'Starting at $3/M input tokens',
          'output_price': r'Starting at $15/M output tokens',
          'released_at': 'Created Sep 29, 2025',
          'reasoning': false,
          'vision': false,
        },
        {
          'name': 'OpenAI: o3',
          'model_id': 'openai/o3',
          'context_window': '200,000 context',
          'input_price': r'$2/M input tokens',
          'output_price': r'$8/M output tokens',
          'released_at': 'Created Apr 16, 2025',
          'reasoning': true,
          'vision': false,
        },
      ],
    },
    {
      'is_preset': true,
      'api_key': '',
      'name': '阿里云百炼',
      'base_url': 'https://dashscope.aliyuncs.com/compatible-mode/v1',
      'models': [
        {
          'name': 'DeepSeek-R1',
          'model_id': 'deepseek-r1',
          'context_window': '131,072 context',
          'input_price': '¥0.004/K input tokens',
          'output_price': '¥0.016/K output tokens',
          'released_at': 'Created 2025-05-28',
          'reasoning': true,
          'vision': false,
        },
        {
          'name': 'DeepSeek-V3',
          'model_id': 'deepseek-v3',
          'context_window': '65,536 context',
          'input_price': '¥0.002/K input tokens',
          'output_price': '¥0.008/K output tokens',
          'released_at': 'Created 2024-12-26',
          'reasoning': false,
          'vision': false,
        },
        {
          'name': '通义千问-Max',
          'model_id': 'qwen-max',
          'context_window': '32,768 context',
          'input_price': '¥0.0024/K input tokens',
          'output_price': '¥0.0096/K output tokens',
          'released_at': 'Created 2025-04-09',
          'reasoning': false,
          'vision': false,
        },
        {
          'name': '通义千问-Plus',
          'model_id': 'qwen-plus',
          'context_window': '131,072 context',
          'input_price': '¥0.0008/K input tokens',
          'output_price': '¥0.002/K output tokens',
          'released_at': 'Created 2025-06-24',
          'reasoning': false,
          'vision': false,
        },
        {
          'name': '通义千问-Turbo',
          'model_id': 'qwen-turbo',
          'context_window': '1,000,000 context',
          'input_price': '¥0.0003/K input tokens',
          'output_price': '¥0.0006/K output tokens',
          'released_at': 'Created 2025-06-24',
          'reasoning': false,
          'vision': false,
        },
      ],
    },
    {
      'is_preset': true,
      'api_key': '',
      'name': '硅基流动',
      'base_url': 'https://api.siliconflow.cn/v1',
      'models': [
        {
          'name': 'DeepSeek-R1',
          'model_id': 'deepseek-ai/DeepSeek-R1',
          'context_window': '160K context',
          'input_price': '￥4/M input tokens',
          'output_price': '￥16/M output tokens',
          'released_at': 'Created 2025-05-28',
          'reasoning': true,
          'vision': false,
        },
        {
          'name': 'DeepSeek-V3',
          'model_id': 'deepseek-ai/DeepSeek-V3',
          'context_window': '64K context',
          'input_price': '￥2/M input tokens',
          'output_price': '￥8/M output tokens',
          'released_at': 'Created 2025-03-24',
          'reasoning': false,
          'vision': false,
        },
      ],
    },
    {
      'is_preset': true,
      'api_key': '',
      'name': '火山方舟',
      'base_url': 'https://ark.cn-beijing.volces.com/api/v3',
      'models': [
        {
          'name': 'DeepSeek-R1',
          'model_id': 'deepseek-r1-250528',
          'context_window': '128K context',
          'input_price': '¥4/M input tokens',
          'output_price': '¥16/M output tokens',
          'released_at': 'Created 2025/05/28',
          'reasoning': true,
          'vision': false,
        },
        {
          'name': 'DeepSeek-V3',
          'model_id': 'deepseek-v3-250324',
          'context_window': '128K context',
          'input_price': '¥2/M input tokens',
          'output_price': '¥8/M output tokens',
          'released_at': 'Created 2025/03/24',
          'reasoning': false,
          'vision': false,
        },
        {
          'name': 'Doubao-Seed-1.6-thinking',
          'model_id': 'doubao-seed-1-6-thinking-250615',
          'context_window': '256K context',
          'input_price': 'Starting at ¥0.8/M input tokens',
          'output_price': 'Starting at ¥8/M output tokens',
          'released_at': 'Created 2025/06/15',
          'reasoning': true,
          'vision': false,
        },
        {
          'name': 'Doubao-Seed-1.6-flash',
          'model_id': 'doubao-seed-1-6-flash-250615',
          'context_window': '256K context',
          'input_price': 'Starting at ¥0.15/M input tokens',
          'output_price': 'Starting at ¥1.5/M input tokens',
          'released_at': 'Created 2025/06/15',
          'reasoning': true,
          'vision': false,
        },
      ],
    },
  ];
}
